# Generated by Django 2.1.3 on 2018-12-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='idDelete',
            new_name='isDelete',
        ),
    ]
